### ISSUE TITLE
Missing a lot of JS files in admin

### ISSUE THREAD

**Issue by barbazul** [kirchbergerknorr/owebia_shipping_2#1]
The editor is not working as most of the JS files are missing

**Comment by MichaelFurtner** [comment]
Hello barbazul, thanks for your feedback.
I'm surprised it does not work for you, this is the same code as on magentocommerce and we have tested it successfully.
Could you tell us which files exactly are missing?

**Comment by barbazul** [comment]
Sure. Take a look at the following folder from the original module:

https://github.com/owebia/magento1-module-shipping-free/tree/master/js/owebia/shipping2

Now look at the same folder in this repo:

https://github.com/kirchbergerknorr/owebia_shipping_2/tree/master/js/owebia/shipping2
